version: '3'
services:
  tex2png:
    image: gudn/tex2png
    ports:
    - 3000:8080
    tmpfs:
    - /tmp
  amrender:
    build: .`
    image: gudn/amrender
    env_file: ./TOKEN
    depends_on:
    - tex2png
